"""
Content Analysis Rules and Rewrite Rules.

Ported from frontend/app.js - preserves rule IDs, categories, patterns,
messages, fixes, and colors exactly as defined in the JavaScript source.
"""

import re


# =============================================================================
# CONTENT ANALYSIS RULES (CA_RULES)
# =============================================================================

CA_RULES = [
    {"id": 'double_negative', "cat": 'Grammar',
     "pattern": re.compile(r"""\b(not|never|no)\b[^.!?\n]{0,90}\b(not|never|no|neither|nor)\b""", re.IGNORECASE),
     "msg": 'Double negative detected. Rewrite using positive phrasing.', "color": 'ca-warn'},
    {"id": 'subjunctive', "cat": 'Grammar',
     "pattern": re.compile(r"""\b(if I were|if he were|if she were|if they were|if it were|were to)\b""", re.IGNORECASE),
     "msg": 'Avoid subjunctive mood. Rewrite in indicative or imperative mood.', "color": 'ca-warn'},
    {"id": 'discontinuous_phrasal', "cat": 'Grammar',
     "pattern": re.compile(r"""\b(turn|switch|shut|close)\s+(?:the\s+)?\w+\s+(off|on|up|down)\b""", re.IGNORECASE),
     "msg": 'Keep phrasal verbs together (e.g., "turn off the device", not "turn the device off").', "color": 'ca-warn'},
    {"id": 'missing_that', "cat": 'Grammar',
     "pattern": re.compile(r"""\b(ensure|confirm|specify|note|verify|check)\s+(it|the|a|an|this|that|these|those|you|we|they|he|she)\b""", re.IGNORECASE),
     "msg": 'Include "that" in relative clauses (e.g., "Ensure that the file is saved").', "color": 'ca-warn'},
    {"id": 'in_order_to', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bin order to\b""", re.IGNORECASE),
     "msg": 'Replace "in order to" with "to".', "fix": 'to', "color": 'ca-replace'},
    {"id": 'due_to_fact', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bdue to the fact that\b""", re.IGNORECASE),
     "msg": 'Replace "due to the fact that" with "because".', "fix": 'because', "color": 'ca-replace'},
    {"id": 'as_consequence', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bas a consequence of\b""", re.IGNORECASE),
     "msg": 'Replace "as a consequence of" with "because of".', "fix": 'because of', "color": 'ca-replace'},
    {"id": 'you_have_to', "cat": 'Word Usage',
     "pattern": re.compile(r"""\byou have to\b""", re.IGNORECASE),
     "msg": 'Use "you must" to express a requirement.', "fix": 'you must', "color": 'ca-replace'},
    {"id": 'you_ought_to', "cat": 'Word Usage',
     "pattern": re.compile(r"""\byou ought to\b""", re.IGNORECASE),
     "msg": 'Use "you should" to express a recommendation.', "fix": 'you should', "color": 'ca-replace'},
    {"id": 'recommended_that', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bit is recommended that you\b""", re.IGNORECASE),
     "msg": 'Replace with "you should".', "fix": 'you should', "color": 'ca-replace'},
    {"id": 'simply', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bsimply\b""", re.IGNORECASE),
     "msg": 'Remove vague modifier "simply".', "fix": '', "color": 'ca-remove'},
    {"id": 'easily', "cat": 'Word Usage',
     "pattern": re.compile(r"""\beasily\b""", re.IGNORECASE),
     "msg": 'Remove vague modifier "easily".', "fix": '', "color": 'ca-remove'},
    {"id": 'quickly', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bquickly\b""", re.IGNORECASE),
     "msg": 'Remove vague modifier "quickly".', "fix": '', "color": 'ca-remove'},
    {"id": 'very', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bvery\b""", re.IGNORECASE),
     "msg": 'Remove vague modifier "very".', "fix": '', "color": 'ca-remove'},
    {"id": 'really', "cat": 'Word Usage',
     "pattern": re.compile(r"""\breally\b""", re.IGNORECASE),
     "msg": 'Remove vague modifier "really".', "fix": '', "color": 'ca-remove'},
    {"id": 'quite', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bquite\b""", re.IGNORECASE),
     "msg": 'Remove vague modifier "quite".', "fix": '', "color": 'ca-remove'},
    {"id": 'obviously', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bobviously\b""", re.IGNORECASE),
     "msg": 'Remove vague modifier "obviously".', "fix": '', "color": 'ca-remove'},
    {"id": 'actually', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bactually\b""", re.IGNORECASE),
     "msg": 'Remove vague modifier "actually".', "fix": '', "color": 'ca-remove'},
    {"id": 'just', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bjust\b""", re.IGNORECASE),
     "msg": 'Remove vague modifier "just" unless meaning changes without it.', "fix": '', "color": 'ca-remove'},
    {"id": 'leverage', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bleverage\b""", re.IGNORECASE),
     "msg": 'Replace jargon "leverage" with "use".', "fix": 'use', "color": 'ca-replace'},
    {"id": 'utilize', "cat": 'Word Usage',
     "pattern": re.compile(r"""\butilize\b""", re.IGNORECASE),
     "msg": 'Replace "utilize" with "use".', "fix": 'use', "color": 'ca-replace'},
    {"id": 'login_ui', "cat": 'Word Usage',
     "pattern": re.compile(r"""\b(login|log[\s\-]in)\b""", re.IGNORECASE),
     "msg": 'Use "sign in". "Login" and "log in" are not permitted.', "fix": 'sign in', "color": 'ca-replace'},
    {"id": 'logout_ui', "cat": 'Word Usage',
     "pattern": re.compile(r"""\b(logout|log[\s\-]out|logoff|log[\s\-]off)\b""", re.IGNORECASE),
     "msg": 'Use "sign out". "Logout", "log out", and "logoff" are not permitted.', "fix": 'sign out', "color": 'ca-replace'},
    {"id": 'click_on', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bclick on\b""", re.IGNORECASE),
     "msg": 'Use "click" for buttons, not "click on".', "fix": 'click', "color": 'ca-replace'},
    {"id": 'default_adj', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bdefault\s+(value|setting|option|behavior|behaviour|state|mode|view)\b""", re.IGNORECASE),
     "msg": '"Default" must be used as a noun only. Do not use it as an adjective.', "color": 'ca-warn'},
    {"id": 'if_when', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bif/when\b""", re.IGNORECASE),
     "msg": 'Avoid "if/when". Use "if" or "when" depending on the context.', "color": 'ca-warn'},
    {"id": 'either_or_slash', "cat": 'Word Usage',
     "pattern": re.compile(r"""\beither/or\b""", re.IGNORECASE),
     "msg": 'Avoid "either/or". Use "and" or "or".', "color": 'ca-warn'},
    {"id": 'eg', "cat": 'Word Usage',
     "pattern": re.compile(r"""\be\.g\.""", re.IGNORECASE),
     "msg": 'Replace "e.g." with "for example".', "fix": 'for example', "color": 'ca-replace'},
    {"id": 'ie', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bi\.e\.""", re.IGNORECASE),
     "msg": 'Replace "i.e." with "that is".', "fix": 'that is', "color": 'ca-replace'},
    {"id": 'ampersand', "cat": 'Word Usage',
     "pattern": re.compile(r"""(?<![A-Za-z0-9#&])&(?![A-Za-z0-9#;])"""),
     "msg": 'Replace "&" with "and".', "fix": 'and', "color": 'ca-replace'},
    {"id": 'etc_warn', "cat": 'Word Usage',
     "pattern": re.compile(r"""\betc\.""", re.IGNORECASE),
     "msg": 'Avoid "etc." unless the list follows a clear logical progression. Use "such as" to introduce partial lists.', "color": 'ca-warn'},
    {"id": 'and_so_on', "cat": 'Word Usage',
     "pattern": re.compile(r"""\band so on\b""", re.IGNORECASE),
     "msg": 'Replace "and so on" with "such as" or list items explicitly.', "fix": 'such as', "color": 'ca-replace'},
    {"id": 'via', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bvia\b""", re.IGNORECASE),
     "msg": 'Replace "via" with "by", "through", or "with".', "color": 'ca-warn'},
    {"id": 'able_to', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bable to\b""", re.IGNORECASE),
     "msg": 'Replace "able to" with "can".', "fix": 'can', "color": 'ca-replace'},
    {"id": 'activate', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bactivate\b""", re.IGNORECASE),
     "msg": 'Replace "activate" with "start" or "run".', "fix": 'start', "color": 'ca-replace'},
    {"id": 'amend', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bamend\b""", re.IGNORECASE),
     "msg": 'Replace "amend" with "change".', "fix": 'change', "color": 'ca-replace'},
    {"id": 'appears', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bappears?\b""", re.IGNORECASE),
     "msg": 'Replace "appear/appears" with "is displayed" (passive) or "shows" (active).', "color": 'ca-warn'},
    {"id": 'as_a_result', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bas a result\b""", re.IGNORECASE),
     "msg": 'Replace "as a result" with "therefore".', "fix": 'therefore', "color": 'ca-replace'},
    {"id": 'due_to', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bdue to\b(?!\s+the\s+fact)""", re.IGNORECASE),
     "msg": 'Replace "due to" with "because of".', "fix": 'because of', "color": 'ca-replace'},
    {"id": 'make_sure', "cat": 'Word Usage',
     "pattern": re.compile(r"""\b(?:make sure|be sure|take care)\b""", re.IGNORECASE),
     "msg": 'Replace with "ensure".', "fix": 'ensure', "color": 'ca-replace'},
    {"id": 'execute_prog', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bexecute\b""", re.IGNORECASE),
     "msg": 'Replace "execute" with "run" (programs) or "perform" or "complete" (actions).', "fix": 'run', "color": 'ca-replace'},
    {"id": 'finalize', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bfinalize\b""", re.IGNORECASE),
     "msg": 'Replace "finalize" with "finish" or "complete".', "fix": 'complete', "color": 'ca-replace'},
    {"id": 'fetch', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bfetch\b""", re.IGNORECASE),
     "msg": 'Replace "fetch" with "retrieve" or "get".', "fix": 'retrieve', "color": 'ca-replace'},
    {"id": 'hang_resp', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bhang(?:s|ing)?\b(?!\s+(?:over|on|out|around|tight))""", re.IGNORECASE),
     "msg": 'Replace "hang" with "stop responding".', "fix": 'stop responding', "color": 'ca-replace'},
    {"id": 'hard_adj', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bhard to\b""", re.IGNORECASE),
     "msg": 'Replace "hard to" with "difficult to".', "fix": 'difficult to', "color": 'ca-replace'},
    {"id": 'have_to', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bhave to\b""", re.IGNORECASE),
     "msg": 'Replace "have to" with "must".', "fix": 'must', "color": 'ca-replace'},
    {"id": 'impact_verb', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bimpact(?:s|ed|ing)?\b""", re.IGNORECASE),
     "msg": 'Use "affect" (verb) or "effect" (noun) instead of "impact".', "color": 'ca-warn'},
    {"id": 'log_onto', "cat": 'Word Usage',
     "pattern": re.compile(r"""\blog\s+onto\b""", re.IGNORECASE),
     "msg": 'Use "sign in" instead of "log onto".', "fix": 'sign in', "color": 'ca-replace'},
    {"id": 'populate', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bpopulate\b""", re.IGNORECASE),
     "msg": 'Replace "populate" with "fill".', "fix": 'fill', "color": 'ca-replace'},
    {"id": 'prior_to', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bprior to\b""", re.IGNORECASE),
     "msg": 'Replace "prior to" with "before".', "fix": 'before', "color": 'ca-replace'},
    {"id": 'toggle', "cat": 'Word Usage',
     "pattern": re.compile(r"""\btoggle\b""", re.IGNORECASE),
     "msg": 'Replace "toggle" with "switch" or "change".', "fix": 'switch', "color": 'ca-replace'},
    {"id": 'whether_or_not', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bwhether or not\b""", re.IGNORECASE),
     "msg": 'Replace "whether or not" with "whether".', "fix": 'whether', "color": 'ca-replace'},
    {"id": 'hover_no_over', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bhover\b(?!\s+over)""", re.IGNORECASE),
     "msg": 'Use "hover over", not just "hover".', "fix": 'hover over', "color": 'ca-replace'},
    {"id": 'such_as_etc', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bsuch as\b[^.!?\n]{0,80}\betc\.""", re.IGNORECASE),
     "msg": 'Do not combine "such as" with "etc." Use one or the other.', "color": 'ca-warn'},
    {"id": 'vague_this', "cat": 'Pronouns',
     "pattern": re.compile(r"""\bThis\s+(is|was|can|will|has|have|enables|allows|means|refers|indicates|helps|provides|ensures|makes|requires)\b"""),
     "msg": 'Vague pronoun "This". Add a noun to clarify (e.g., "This process is…").', "color": 'ca-warn'},
    {"id": 'vague_these', "cat": 'Pronouns',
     "pattern": re.compile(r"""\bThese\s+(are|were|can|will|have|enable|allow|include|ensure|make|require)\b"""),
     "msg": 'Vague pronoun "These". Add a noun (e.g., "These settings are…").', "color": 'ca-warn'},
    {"id": 'vague_those', "cat": 'Pronouns',
     "pattern": re.compile(r"""\bThose\s+(are|were|can|will|have|enable|allow|include|require)\b"""),
     "msg": 'Vague pronoun "Those". Add a noun to clarify the antecedent.', "color": 'ca-warn'},
    {"id": 'which_clause', "cat": 'Pronouns',
     "pattern": re.compile(r""",\s*which\b""", re.IGNORECASE),
     "msg": '"Which" after a comma may refer to the entire preceding clause. Split into two sentences.', "color": 'ca-warn'},
    {"id": 'gender_pronoun', "cat": 'Pronouns',
     "pattern": re.compile(r"""\b(he|she|he/she|s/he)\b"""),
     "msg": 'Use gender-neutral language. Replace gendered pronouns with "they", "their", or rewrite using plural forms.', "color": 'ca-warn'},
    {"id": 'please', "cat": 'Style & Tone',
     "pattern": re.compile(r"""\bplease\b""", re.IGNORECASE),
     "msg": 'Remove politeness marker "please". Technical writing must be direct and neutral.', "fix": '', "color": 'ca-remove'},
    {"id": 'kindly', "cat": 'Style & Tone',
     "pattern": re.compile(r"""\bkindly\b""", re.IGNORECASE),
     "msg": 'Remove politeness marker "kindly".', "fix": '', "color": 'ca-remove'},
    {"id": 'blacklist', "cat": 'Style & Tone',
     "pattern": re.compile(r"""\bblacklist(?:ed|ing|s)?\b""", re.IGNORECASE),
     "msg": 'Replace biased term "blacklist" with "blocklist" or "denylist".', "fix": 'blocklist', "color": 'ca-remove'},
    {"id": 'whitelist', "cat": 'Style & Tone',
     "pattern": re.compile(r"""\bwhitelist(?:ed|ing|s)?\b""", re.IGNORECASE),
     "msg": 'Replace biased term "whitelist" with "allowlist".', "fix": 'allowlist', "color": 'ca-remove'},
    {"id": 'master_slave', "cat": 'Style & Tone',
     "pattern": re.compile(r"""\b(master|slave)\b""", re.IGNORECASE),
     "msg": 'Replace "master" or "slave" with "primary/secondary" or "controller/worker".', "color": 'ca-remove'},
    {"id": 'manpower', "cat": 'Style & Tone',
     "pattern": re.compile(r"""\bmanpower\b""", re.IGNORECASE),
     "msg": 'Replace "manpower" with "workforce" or "staff".', "fix": 'workforce', "color": 'ca-remove'},
    {"id": 'kill_term', "cat": 'Style & Tone',
     "pattern": re.compile(r"""\bkill\b""", re.IGNORECASE),
     "msg": 'Replace violent term "kill" with "stop", "end", or "terminate".', "fix": 'stop', "color": 'ca-remove'},
    {"id": 'abort_term', "cat": 'Style & Tone',
     "pattern": re.compile(r"""\babort\b""", re.IGNORECASE),
     "msg": 'Replace "abort" with "cancel" or "stop".', "fix": 'cancel', "color": 'ca-remove'},
    {"id": 'below_ref', "cat": 'Style & Tone',
     "pattern": re.compile(r"""\bbelow\b""", re.IGNORECASE),
     "msg": 'Avoid "below". Reference content by name or section title.', "color": 'ca-warn'},
    {"id": 'following_ref', "cat": 'Style & Tone',
     "pattern": re.compile(r"""\bthe following\b""", re.IGNORECASE),
     "msg": 'Avoid "the following". Use a specific heading or label instead.', "color": 'ca-warn'},
    {"id": 'little_mod', "cat": 'Style & Tone',
     "pattern": re.compile(r"""\blittle\b""", re.IGNORECASE),
     "msg": 'Avoid vague modifier "little". Be specific.', "fix": '', "color": 'ca-remove'},
    {"id": 'greatly_mod', "cat": 'Style & Tone',
     "pattern": re.compile(r"""\bgreatly\b""", re.IGNORECASE),
     "msg": 'Avoid vague modifier "greatly". Be specific.', "fix": '', "color": 'ca-remove'},
    {"id": 'also_start', "cat": 'Style & Tone',
     "pattern": re.compile(r"""\bAlso\b"""),
     "msg": 'Avoid starting a sentence with "Also". Restructure the sentence.', "color": 'ca-warn'},
    {"id": 'minorities', "cat": 'Style & Tone',
     "pattern": re.compile(r"""\bminorities\b""", re.IGNORECASE),
     "msg": 'Replace "minorities" with "underrepresented groups".', "fix": 'underrepresented groups', "color": 'ca-replace'},
    {"id": 'bomb_term', "cat": 'Style & Tone',
     "pattern": re.compile(r"""\bbomb\b""", re.IGNORECASE),
     "msg": 'Avoid violent term "bomb". Rephrase to describe the actual action or event.', "color": 'ca-warn'},
    {"id": 'semicolon', "cat": 'Punctuation',
     "pattern": re.compile(r""";"""),
     "msg": 'Avoid semicolons. Rewrite as two separate sentences.', "color": 'ca-warn'},
    {"id": 'em_dash', "cat": 'Punctuation',
     "pattern": re.compile(r"""\u2014|\u2013"""),
     "msg": 'Avoid em and en dashes. Use a comma or split the sentence.', "color": 'ca-warn'},
    {"id": 'digit_small', "cat": 'Numbers',
     "pattern": re.compile(r"""(?<![A-Za-z0-9./\-#@v])([1-9])(?!\s*(?:st|nd|rd|th)|[0-9%\u00b0/.:\-])"""),
     "msg": 'Spell out numbers less than 10 (e.g., write "five" instead of "5").', "color": 'ca-warn'},
    {"id": 'approx_about', "cat": 'Numbers',
     "pattern": re.compile(r"""\babout\s+\d+\b""", re.IGNORECASE),
     "msg": 'Avoid approximations. Use the exact number instead of "about N".', "color": 'ca-warn'},
    {"id": 'approx_around', "cat": 'Numbers',
     "pattern": re.compile(r"""\baround\s+\d+\b""", re.IGNORECASE),
     "msg": 'Avoid approximations. Use the exact number instead of "around N".', "color": 'ca-warn'},
    {"id": 'approx_approx', "cat": 'Numbers',
     "pattern": re.compile(r"""\bapproximately\s+\d+\b""", re.IGNORECASE),
     "msg": 'Avoid approximations. Use the exact number.', "color": 'ca-warn'},
    {"id": 'based_on', "cat": 'Translation',
     "pattern": re.compile(r"""\bbased on\b""", re.IGNORECASE),
     "msg": 'Ambiguous "based on". Clarify explicitly (e.g., "calculated from", "derived from").', "color": 'ca-warn'},
    {"id": 'need_not', "cat": 'Translation',
     "pattern": re.compile(r"""\bneed not\b""", re.IGNORECASE),
     "msg": 'Ambiguous "need not". Rephrase (e.g., "do not need to").', "fix": 'do not need to', "color": 'ca-warn'},
    {"id": 'must_have_been', "cat": 'Translation',
     "pattern": re.compile(r"""\bmust have been\b""", re.IGNORECASE),
     "msg": 'Ambiguous modal "must have been". Rephrase to remove ambiguity.', "color": 'ca-warn'},
    {"id": 'ambig_it', "cat": 'Translation',
     "pattern": re.compile(r"""\bIt\s+(is|was|can|will|has|have|ensures|enables|allows|provides|means)\b"""),
     "msg": 'Possible vague "It". Ensure the antecedent is explicit and unambiguous.', "color": 'ca-warn'},
    {"id": 'rather_mod', "cat": 'Word Usage',
     "pattern": re.compile(r"""\brather\b""", re.IGNORECASE),
     "msg": 'Remove vague modifier "rather".', "fix": '', "color": 'ca-remove'},
    {"id": 'need_to', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bneed to\b""", re.IGNORECASE),
     "msg": '"Need to" implies personal necessity. Use "must" for required actions or "should" for recommended actions.', "color": 'ca-warn'},
    {"id": 'on_premise', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bon-premise(?!s)\b""", re.IGNORECASE),
     "msg": 'Use "on-premises" (with an "s"), not "on-premise".', "fix": 'on-premises', "color": 'ca-replace'},
    {"id": 'need_personal', "cat": 'Word Usage',
     "pattern": re.compile(r"""\b(I|you|we|they)\s+need\b""", re.IGNORECASE),
     "msg": '"Need" implies personal necessity. Use "require" in formal or technical contexts.', "color": 'ca-warn'},
    {"id": 'displayed_use', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bdisplayed\b""", re.IGNORECASE),
     "msg": 'Avoid "displayed" for screen navigation. Use "access" (e.g., "You can access this screen only if...").', "color": 'ca-warn'},
    {"id": 'foreman_word', "cat": 'Style & Tone',
     "pattern": re.compile(r"""\bforeman\b""", re.IGNORECASE),
     "msg": 'Replace "foreman" with the gender-neutral term "supervisor".', "fix": 'supervisor', "color": 'ca-remove'},
    {"id": 'you_must_not', "cat": 'Style & Tone',
     "pattern": re.compile(r"""\byou must not\b""", re.IGNORECASE),
     "msg": 'Use "do not" instead of "you must not". Write positively.', "fix": 'do not', "color": 'ca-replace'},
    {"id": 'ellipsis', "cat": 'Punctuation',
     "pattern": re.compile(r"""\.{3}|…"""),
     "msg": 'Avoid ellipses. Rewrite the sentence to be complete.', "color": 'ca-warn'},
    {"id": 'and_or_slash', "cat": 'Punctuation',
     "pattern": re.compile(r"""\band/or\b""", re.IGNORECASE),
     "msg": 'Avoid "and/or". Use "and" or "or" depending on the context.', "color": 'ca-warn'},
    {"id": 'contraction', "cat": 'Punctuation',
     "pattern": re.compile(r"""\b(don't|can't|won't|isn't|aren't|wasn't|weren't|hasn't|haven't|hadn't|doesn't|didn't|wouldn't|couldn't|shouldn't|I'm|I've|I'll|I'd|you're|you've|you'll|you'd|he's|she's|it's|we're|we've|we'll|we'd|they're|they've|they'll|they'd|that's|what's|there's|here's|let's|who's|how's)\b"""),
     "msg": 'Expand this contraction. Technical writing must not use contractions.', "color": 'ca-replace'},
    {"id": 'hit_key', "cat": 'UI Conventions',
     "pattern": re.compile(r"""\bhit\b""", re.IGNORECASE),
     "msg": 'Use "press" for keyboard keys, not "hit".', "fix": 'press', "color": 'ca-replace'},
    {"id": 'push_button', "cat": 'UI Conventions',
     "pattern": re.compile(r"""\bpush\b""", re.IGNORECASE),
     "msg": 'Use "click" for buttons, not "push".', "fix": 'click', "color": 'ca-replace'},
    {"id": 'click_at', "cat": 'UI Conventions',
     "pattern": re.compile(r"""\bclick\s+at\b""", re.IGNORECASE),
     "msg": 'Use "click", not "click at".', "fix": 'click', "color": 'ca-replace'},
    {"id": 'dialog_no_box', "cat": 'UI Conventions',
     "pattern": re.compile(r"""\bdialog(?!\s*box)\b""", re.IGNORECASE),
     "msg": 'Use "dialog box", not just "dialog". The full term is required.', "fix": 'dialog box', "color": 'ca-replace'},
    {"id": 'submenu_word', "cat": 'UI Conventions',
     "pattern": re.compile(r"""\bsubmenu\b""", re.IGNORECASE),
     "msg": 'Avoid "submenu". Describe the specific menu path instead.', "color": 'ca-warn'},
    {"id": 'navigate_to', "cat": 'UI Conventions',
     "pattern": re.compile(r"""\bnavigate to\b""", re.IGNORECASE),
     "msg": 'Use "access" instead of "navigate to" when referring to screens or pages.', "fix": 'access', "color": 'ca-replace'},
    {"id": 'screen_displayed', "cat": 'UI Conventions',
     "pattern": re.compile(r"""\b(?:screen|page|window|session)\s+(?:is|are)\s+displayed\b""", re.IGNORECASE),
     "msg": 'Use "access" when referring to navigating to a screen, page, or session (e.g., "You can access this screen only if...").', "color": 'ca-warn'},
    {"id": 'elderly_seniors', "cat": 'Style & Tone',
     "pattern": re.compile(r"""\b(the elderly|elderly people|senior citizens|seniors(?!\s+(?:manager|developer|executive|analyst|architect|vice|director|level|leadership|position|role|staff|member|team)))\b""", re.IGNORECASE),
     "msg": 'Replace "the elderly" or "seniors" with "older adults".', "fix": 'older adults', "color": 'ca-replace'},
    {"id": 'web_site', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bweb\s+site\b""", re.IGNORECASE),
     "msg": 'Use "website" as one word, not "web site".', "fix": 'website', "color": 'ca-replace'},
    {"id": 'amount_for_qty', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bamount\s+of\s+(?:items|records|entries|rows|documents|files|users|accounts|lines|tasks|results|transactions|orders|products|parts|units|tickets|requests)\b""", re.IGNORECASE),
     "msg": 'Use "quantity" for countable items, not "amount". "Amount" is for uncountable or monetary values.', "fix": 'quantity of', "color": 'ca-replace'},
    {"id": 'qty_for_amount', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bquantity\s+of\s+(?:money|dollars|euros|pounds|currency|funds|budget|costs?|prices?|revenue|payment|expenses?|fees?|charges?)\b""", re.IGNORECASE),
     "msg": 'Use "amount" for monetary values, not "quantity". "Quantity" is for countable items.', "fix": 'amount of', "color": 'ca-replace'},
    {"id": 'number_of_money', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bnumber\s+of\s+(?:money|dollars|euros|pounds|currency|funds|budget|costs?|prices?|revenue|payment|expenses?)\b""", re.IGNORECASE),
     "msg": 'Use "amount" for monetary values, not "number of".', "fix": 'amount of', "color": 'ca-replace'},
    {"id": 'dialog_standalone', "cat": 'Word Usage',
     "pattern": re.compile(r"""\bdialog\b(?!\s*box)""", re.IGNORECASE),
     "msg": 'Use "dialog box" (the full term), not "dialog" alone.', "fix": 'dialog box', "color": 'ca-replace'},
    {"id": 'uncheck_word', "cat": 'UI Conventions',
     "pattern": re.compile(r"""\buncheck\b""", re.IGNORECASE),
     "msg": 'Use "Clear" to deselect a check box, not "uncheck".', "fix": 'Clear', "color": 'ca-replace'},
    {"id": 'deselect_word', "cat": 'UI Conventions',
     "pattern": re.compile(r"""\bdeselect\b""", re.IGNORECASE),
     "msg": 'Use "Clear" to deselect an option, not "deselect".', "fix": 'Clear', "color": 'ca-replace'},
    {"id": 'check_checkbox', "cat": 'UI Conventions',
     "pattern": re.compile(r"""\bcheck\s+(?:the\s+|a\s+)?(?:\w+\s+)?(?:check\s*box|checkbox)\b""", re.IGNORECASE),
     "msg": 'Use "Select" for check boxes, not "check". Example: "Select the check box."', "fix": 'Select the check box', "color": 'ca-replace'},
    {"id": 'tick_checkbox', "cat": 'UI Conventions',
     "pattern": re.compile(r"""\btick\s+(?:the\s+|a\s+)?(?:\w+\s+)?(?:check\s*box|checkbox)\b""", re.IGNORECASE),
     "msg": 'Use "Select" for check boxes, not "tick".', "fix": 'Select', "color": 'ca-replace'},
    {"id": 'press_enter_vs_click', "cat": 'UI Conventions',
     "pattern": re.compile(r"""\bclick\s+(?:the\s+)?(?:Enter|Return|Tab|Escape|Esc|Delete|Backspace|Ctrl|Alt|Shift|Spacebar|Space bar|F\d{1,2})\b""", re.IGNORECASE),
     "msg": 'Use "Press" for keyboard keys, not "Click".', "fix": 'Press', "color": 'ca-replace'},
    {"id": 'select_from_menu', "cat": 'UI Conventions',
     "pattern": re.compile(r"""\bchoose\s+(?:from\s+)?(?:the\s+)?(?:\w+\s+)?(?:menu|list|drop-?down)\b""", re.IGNORECASE),
     "msg": 'Use "Select" when choosing from a menu or list.', "fix": 'Select', "color": 'ca-replace'},
    {"id": 'specify_text_field', "cat": 'UI Conventions',
     "pattern": re.compile(r"""\b(?:type|enter)\s+(?:the\s+|a\s+|your\s+)?\w[\w\s]{0,30}(?:in(?:to)?\s+the\s+\w+\s+field|in(?:to)?\s+the\s+\w+\s+box)\b""", re.IGNORECASE),
     "msg": 'Use "Specify" when instructing users to fill in a text field. Example: "Specify the name in the Name field."', "color": 'ca-warn'},
    {"id": 'open_vs_access', "cat": 'UI Conventions',
     "pattern": re.compile(r"""\bopen\s+(?:the\s+)?(?:\w+\s+)?(?:screen|page|window|form|tab)\b""", re.IGNORECASE),
     "msg": 'Use "access" instead of "open" when navigating to a screen, page, or window.', "fix": 'access', "color": 'ca-replace'},
    {"id": 'step_not_verb', "cat": 'Grammar',
     "pattern": re.compile(r"""^(?:\d+[.)]\s+)(?:The |A |An |This |These |Your |My |Our |Their |Its |All |Each |Every )""", re.MULTILINE),
     "msg": 'Task steps must start with a verb (imperative mood). This step appears to start with a noun, article, or possessive.', "color": 'ca-warn'},
    {"id": 'future_tense_ui', "cat": 'Grammar',
     "pattern": re.compile(r"""\bwill\s+(?:be\s+)?(?:display|show|appear|open|close|update|refresh|load|save|create|delete|add|remove|enable|disable|generate|populate|calculate|validate|process)\b""", re.IGNORECASE),
     "msg": 'Use simple present tense for current software actions. Use future tense only for actions clearly occurring in the future.', "color": 'ca-warn'},
    {"id": 'action_noun_as_verb', "cat": 'Grammar',
     "pattern": re.compile(r"""\bto\s+action\b""", re.IGNORECASE),
     "msg": 'Do not use "action" as a verb. Rewrite using "perform", "complete", or a specific action verb.', "color": 'ca-warn'},
    {"id": 'solution_verb', "cat": 'Grammar',
     "pattern": re.compile(r"""\bsolution\s+(?:this|that|the)\b""", re.IGNORECASE),
     "msg": 'Do not use "solution" as a verb. Use "resolve" or "fix".', "color": 'ca-warn'},
    {"id": 'impact_as_verb', "cat": 'Grammar',
     "pattern": re.compile(r"""\b(?:this|that|it|the\s+\w+)\s+impact(?:s|ed)?\b""", re.IGNORECASE),
     "msg": 'Do not use "impact" as a verb. Use "affect" (verb) or "effect" (noun).', "fix": 'affects', "color": 'ca-replace'},
    {"id": 'double_space', "cat": 'Punctuation',
     "pattern": re.compile(r"""[ \t]{2,}"""),
     "msg": 'Use a single space between words. Remove the extra space.', "fix": ' ', "color": 'ca-replace'},
    {"id": 'dep_clause_if', "cat": 'Punctuation',
     "pattern": re.compile(r"""(?:^|\.\s+)If\s+[^,\n.]{20,}[^,\n]\s+(?:you\b|the\b|a\b|an\b|it\b|select\b|click\b|type\b|enter\b|specify\b|choose\b)""", re.MULTILINE),
     "msg": 'Add a comma after an introductory "If" clause. Example: "If the field is empty, specify a value."', "color": 'ca-warn'},
    {"id": 'dep_clause_when', "cat": 'Punctuation',
     "pattern": re.compile(r"""(?:^|\.\s+)When\s+[^,\n.]{20,}[^,\n]\s+(?:you\b|the\b|a\b|an\b|it\b|select\b|click\b|type\b|enter\b|specify\b|choose\b)""", re.MULTILINE),
     "msg": 'Add a comma after an introductory "When" clause. Example: "When the process completes, the status changes."', "color": 'ca-warn'},
    {"id": 'dep_clause_after', "cat": 'Punctuation',
     "pattern": re.compile(r"""(?:^|\.\s+)After\s+[^,\n.]{15,}[^,\n]\s+(?:you\b|the\b|a\b|an\b|it\b|select\b|click\b|type\b|enter\b|specify\b|choose\b)""", re.MULTILINE),
     "msg": 'Add a comma after an introductory "After" clause. Example: "After you save the record, the list refreshes."', "color": 'ca-warn'},
    {"id": 'slash_separator', "cat": 'Punctuation',
     "pattern": re.compile(r"""(?<![:/])\b\w+/\w+\b"""),
     "msg": 'Avoid using a slash as a separator. Rewrite using "and", "or", or rewrite the sentence.', "color": 'ca-warn'},
    {"id": 'ordinal_spell_small', "cat": 'Numbers',
     "pattern": re.compile(r"""\b(1st|2nd|3rd|4th|5th|6th|7th|8th|9th)\b"""),
     "msg": 'Spell out ordinal numbers below 10 (e.g., "first", "second", "third").', "color": 'ca-warn'},
    {"id": 'may_ambig', "cat": 'Translation',
     "pattern": re.compile(r"""\b(?:you\s+)?may\s+(?:also\s+)?(?:want\s+to\s+|wish\s+to\s+)?(?:[a-z]+)\b""", re.IGNORECASE),
     "msg": '"May" is ambiguous — it can mean permission or possibility. Use "can" for permission or "might" for possibility.', "color": 'ca-warn'},
    {"id": 'should_ambig_passive', "cat": 'Translation',
     "pattern": re.compile(r"""\bshould\s+be\s+(?:noted|mentioned|understood|known|remembered|highlighted)\b""", re.IGNORECASE),
     "msg": 'Avoid passive constructions with "should be noted". Rewrite as an active statement.', "color": 'ca-warn'},
    {"id": 'once_ambig', "cat": 'Translation',
     "pattern": re.compile(r"""\bonce\b""", re.IGNORECASE),
     "msg": '"Once" is ambiguous — it can mean "after" (temporal) or "one time only". Use "after" or "when" for clarity.', "color": 'ca-warn'},
    {"id": 'since_ambig', "cat": 'Translation',
     "pattern": re.compile(r"""\bsince\b""", re.IGNORECASE),
     "msg": '"Since" is ambiguous — it can mean "because" or "from that time". Use "because" or "after" to remove ambiguity.', "color": 'ca-warn'},
    {"id": 'while_ambig', "cat": 'Translation',
     "pattern": re.compile(r"""\bwhile\b""", re.IGNORECASE),
     "msg": '"While" is ambiguous — it can mean "although" or "at the same time as". Use "although" or "when" for clarity.', "color": 'ca-warn'},
]


# =============================================================================
# REWRITE RULES (RW_RULES)
# =============================================================================

RW_RULES = [
    {"type": 'replace',
     "pattern": re.compile(r"""\bin order (?:to|for)\b""", re.IGNORECASE),
     "msg": 'in order to → to', "fix": 'to'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bdue to the fact that\b""", re.IGNORECASE),
     "msg": 'due to the fact that → because', "fix": 'because'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bfor the reason that\b""", re.IGNORECASE),
     "msg": 'for the reason that → because', "fix": 'because'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bas a consequence of\b""", re.IGNORECASE),
     "msg": 'as a consequence of → because of', "fix": 'because of'},
    {"type": 'replace',
     "pattern": re.compile(r"""\byou have to\b""", re.IGNORECASE),
     "msg": 'you have to → you must', "fix": 'you must'},
    {"type": 'replace',
     "pattern": re.compile(r"""\byou ought to\b""", re.IGNORECASE),
     "msg": 'you ought to → you should', "fix": 'you should'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bit is recommended that you\b""", re.IGNORECASE),
     "msg": 'it is recommended that you → you should', "fix": 'you should'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bif you want to\b""", re.IGNORECASE),
     "msg": 'if you want to → to', "fix": 'to'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bto be able to\b""", re.IGNORECASE),
     "msg": 'to be able to → to', "fix": 'to'},
    {"type": 'remove',
     "pattern": re.compile(r"""\bin some (?:cases|circumstances)\b[,]?\s*""", re.IGNORECASE),
     "msg": 'remove: in some cases'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bon the basis of\b""", re.IGNORECASE),
     "msg": 'on the basis of → based on', "fix": 'based on'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bprior to\b""", re.IGNORECASE),
     "msg": 'prior to → before', "fix": 'before'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bonce\s+(you|the|a|an|it|they|we|this)\b""", re.IGNORECASE),
     "msg": 'once (temporal) → after', "fix": 'After $1'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bvia\b""", re.IGNORECASE),
     "msg": 'via → through', "fix": 'through'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bby means of\b""", re.IGNORECASE),
     "msg": 'by means of → using', "fix": 'using'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bin relation to\b""", re.IGNORECASE),
     "msg": 'in relation to → about', "fix": 'about'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bwhether or not\b""", re.IGNORECASE),
     "msg": 'whether or not → whether', "fix": 'whether'},
    {"type": 'remove',
     "pattern": re.compile(r"""\b(?:this|which) means that\b[,]?\s*""", re.IGNORECASE),
     "msg": 'remove: this/which means that'},
    {"type": 'remove',
     "pattern": re.compile(r"""\bthe system requires you to\b\s*""", re.IGNORECASE),
     "msg": 'remove: the system requires you to'},
    {"type": 'remove',
     "pattern": re.compile(r"""\btake these steps\b[:]?\s*""", re.IGNORECASE),
     "msg": 'remove: take these steps'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bkeep in mind(?:\s+that)?\b""", re.IGNORECASE),
     "msg": 'keep in mind → Note:', "fix": 'Note:'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bat all times\b""", re.IGNORECASE),
     "msg": 'at all times → always', "fix": 'always'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bsanity check\b""", re.IGNORECASE),
     "msg": 'sanity check → verification', "fix": 'verification'},
    {"type": 'remove',
     "pattern": re.compile(r"""\bback burner\b""", re.IGNORECASE),
     "msg": 'remove: back burner'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bballpark figure\b""", re.IGNORECASE),
     "msg": 'ballpark figure → estimate', "fix": 'estimate'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bclick\s+(?:on|at)\b""", re.IGNORECASE),
     "msg": 'click on/at → click', "fix": 'click'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bhit\s+(the\s+)?(?=\w)""", re.IGNORECASE),
     "msg": 'hit → click', "fix": 'click the '},
    {"type": 'replace',
     "pattern": re.compile(r"""\b(?:login|log[\s\-]in|log[\s\-]on)\b""", re.IGNORECASE),
     "msg": 'login/log in → sign in', "fix": 'sign in'},
    {"type": 'replace',
     "pattern": re.compile(r"""\b(?:logout|log[\s\-]out|log[\s\-]off|logoff)\b""", re.IGNORECASE),
     "msg": 'logout/log out → sign out', "fix": 'sign out'},
    {"type": 'replace',
     "pattern": re.compile(r"""\benter\s+(the|a|an|your)\b""", re.IGNORECASE),
     "msg": 'enter → specify (for text fields)', "fix": 'specify $1'},
    {"type": 'replace',
     "pattern": re.compile(r"""\btoggle\b""", re.IGNORECASE),
     "msg": 'toggle → switch', "fix": 'switch'},
    {"type": 'replace',
     "pattern": re.compile(r"""\b(?:grayed[\s\-]out|dimmed)\b""", re.IGNORECASE),
     "msg": 'grayed out/dimmed → not available', "fix": 'not available'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bdialog(?!\s+box)\b""", re.IGNORECASE),
     "msg": 'dialog → dialog box', "fix": 'dialog box'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bsub[\-]?menu\b""", re.IGNORECASE),
     "msg": 'submenu → menu', "fix": 'menu'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bfilename\b""", re.IGNORECASE),
     "msg": 'filename → file name', "fix": 'file name'},
    {"type": 'replace',
     "pattern": re.compile(r"""\b[Ww]eb\s+[Ss]ite\b"""),
     "msg": 'web site → website', "fix": 'website'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bon[\-]premise(?!s)\b""", re.IGNORECASE),
     "msg": 'on-premise → on-premises', "fix": 'on-premises'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bon[\-]line\b""", re.IGNORECASE),
     "msg": 'on-line → online', "fix": 'online'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bpopulate\b""", re.IGNORECASE),
     "msg": 'populate → add', "fix": 'add'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bexecute\b""", re.IGNORECASE),
     "msg": 'execute → run', "fix": 'run'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bleverage\b""", re.IGNORECASE),
     "msg": 'leverage → use', "fix": 'use'},
    {"type": 'replace',
     "pattern": re.compile(r"""\butilize\b""", re.IGNORECASE),
     "msg": 'utilize → use', "fix": 'use'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bimpact\b(?!\s+(?:analysis|report|assessment))""", re.IGNORECASE),
     "msg": 'impact (verb) → affect', "fix": 'affect'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bdesigned to\b""", re.IGNORECASE),
     "msg": 'designed to → (remove)', "fix": ''},
    {"type": 'replace',
     "pattern": re.compile(r"""\bkill\b""", re.IGNORECASE),
     "msg": 'kill → stop', "fix": 'stop'},
    {"type": 'replace',
     "pattern": re.compile(r"""\babort\b""", re.IGNORECASE),
     "msg": 'abort → cancel', "fix": 'cancel'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bstop\s+responding\b""", re.IGNORECASE),
     "msg": 'stop responding → not respond', "fix": 'not respond'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bprogram\b""", re.IGNORECASE),
     "msg": 'program → application', "fix": 'application'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bblacklist(?:ed|ing|s)?\b""", re.IGNORECASE),
     "msg": 'blacklist → blocklist', "fix": 'blocklist'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bwhitelist(?:ed|ing|s)?\b""", re.IGNORECASE),
     "msg": 'whitelist → allowlist', "fix": 'allowlist'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bmaster\b(?!\s+(?:class|copy|plan|data))""", re.IGNORECASE),
     "msg": 'master → primary', "fix": 'primary'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bslave\b""", re.IGNORECASE),
     "msg": 'slave → secondary', "fix": 'secondary'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bmanpower\b""", re.IGNORECASE),
     "msg": 'manpower → workforce', "fix": 'workforce'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bmanmade\b""", re.IGNORECASE),
     "msg": 'manmade → manufactured', "fix": 'manufactured'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bman[\s\-]hours?\b""", re.IGNORECASE),
     "msg": 'man hours → work hours', "fix": 'work hours'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bmankind\b""", re.IGNORECASE),
     "msg": 'mankind → people', "fix": 'people'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bchairman\b""", re.IGNORECASE),
     "msg": 'chairman → chair', "fix": 'chair'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bhe/she\b""", re.IGNORECASE),
     "msg": 'he/she → they', "fix": 'they'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bhe or she\b""", re.IGNORECASE),
     "msg": 'he or she → they', "fix": 'they'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bdummy\b""", re.IGNORECASE),
     "msg": 'dummy → sample', "fix": 'sample'},
    {"type": 'remove',
     "pattern": re.compile(r"""\bplease\b[,]?\s*""", re.IGNORECASE),
     "msg": 'remove: please'},
    {"type": 'remove',
     "pattern": re.compile(r"""\bkindly\b[,]?\s*""", re.IGNORECASE),
     "msg": 'remove: kindly'},
    {"type": 'remove',
     "pattern": re.compile(r"""\bvery\b\s*""", re.IGNORECASE),
     "msg": 'remove: very'},
    {"type": 'remove',
     "pattern": re.compile(r"""\breally\b\s*""", re.IGNORECASE),
     "msg": 'remove: really'},
    {"type": 'remove',
     "pattern": re.compile(r"""\bquite\b\s*""", re.IGNORECASE),
     "msg": 'remove: quite'},
    {"type": 'remove',
     "pattern": re.compile(r"""\bsimply\b\s*""", re.IGNORECASE),
     "msg": 'remove: simply'},
    {"type": 'remove',
     "pattern": re.compile(r"""\beasily\b\s*""", re.IGNORECASE),
     "msg": 'remove: easily'},
    {"type": 'remove',
     "pattern": re.compile(r"""\bquickly\b\s*""", re.IGNORECASE),
     "msg": 'remove: quickly'},
    {"type": 'remove',
     "pattern": re.compile(r"""\bobviously\b[,]?\s*""", re.IGNORECASE),
     "msg": 'remove: obviously'},
    {"type": 'remove',
     "pattern": re.compile(r"""\bactually\b[,]?\s*""", re.IGNORECASE),
     "msg": 'remove: actually'},
    {"type": 'remove',
     "pattern": re.compile(r"""\bjust\b\s*""", re.IGNORECASE),
     "msg": 'remove: just'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bi\.e\.,?\s*""", re.IGNORECASE),
     "msg": 'i.e. → that is', "fix": 'that is, '},
    {"type": 'replace',
     "pattern": re.compile(r"""\be\.g\.,?\s*""", re.IGNORECASE),
     "msg": 'e.g. → for example', "fix": 'for example, '},
    {"type": 'replace',
     "pattern": re.compile(r"""\bdefault(?:s|ed|ing)?\s+to\b""", re.IGNORECASE),
     "msg": 'default (verb) → sets the default to', "fix": 'sets the default to'},
    {"type": 'replace',
     "pattern": re.compile(r""";\s*"""),
     "msg": 'semicolon → period', "fix": '. '},
    {"type": 'replace',
     "pattern": re.compile(r"""\bcan't\b""", re.IGNORECASE),
     "msg": "can't → cannot", "fix": 'cannot'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bwon't\b""", re.IGNORECASE),
     "msg": "won't → do not", "fix": 'do not'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bdon't\b""", re.IGNORECASE),
     "msg": "don't → do not", "fix": 'do not'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bdoesn't\b""", re.IGNORECASE),
     "msg": "doesn't → does not", "fix": 'does not'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bdidn't\b""", re.IGNORECASE),
     "msg": "didn't → did not", "fix": 'did not'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bisn't\b""", re.IGNORECASE),
     "msg": "isn't → is not", "fix": 'is not'},
    {"type": 'replace',
     "pattern": re.compile(r"""\baren't\b""", re.IGNORECASE),
     "msg": "aren't → are not", "fix": 'are not'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bwasn't\b""", re.IGNORECASE),
     "msg": "wasn't → was not", "fix": 'was not'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bweren't\b""", re.IGNORECASE),
     "msg": "weren't → were not", "fix": 'were not'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bhasn't\b""", re.IGNORECASE),
     "msg": "hasn't → has not", "fix": 'has not'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bhaven't\b""", re.IGNORECASE),
     "msg": "haven't → have not", "fix": 'have not'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bhadn't\b""", re.IGNORECASE),
     "msg": "hadn't → had not", "fix": 'had not'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bit's\b""", re.IGNORECASE),
     "msg": "it's → it is", "fix": 'it is'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bthat's\b""", re.IGNORECASE),
     "msg": "that's → that is", "fix": 'that is'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bthere's\b""", re.IGNORECASE),
     "msg": "there's → there is", "fix": 'there is'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bthey're\b""", re.IGNORECASE),
     "msg": "they're → they are", "fix": 'they are'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bwe're\b""", re.IGNORECASE),
     "msg": "we're → we are", "fix": 'we are'},
    {"type": 'replace',
     "pattern": re.compile(r"""\byou're\b""", re.IGNORECASE),
     "msg": "you're → you are", "fix": 'you are'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bwe've\b""", re.IGNORECASE),
     "msg": "we've → we have", "fix": 'we have'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bthey've\b""", re.IGNORECASE),
     "msg": "they've → they have", "fix": 'they have'},
    {"type": 'replace',
     "pattern": re.compile(r"""\byou've\b""", re.IGNORECASE),
     "msg": "you've → you have", "fix": 'you have'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bI'm\b"""),
     "msg": "I'm → I am", "fix": 'I am'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bwouldn't\b""", re.IGNORECASE),
     "msg": "wouldn't → do not", "fix": 'do not'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bcouldn't\b""", re.IGNORECASE),
     "msg": "couldn't → cannot", "fix": 'cannot'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bshouldn't\b""", re.IGNORECASE),
     "msg": "shouldn't → must not", "fix": 'must not'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bwill\s+be\s+able\s+to\b""", re.IGNORECASE),
     "msg": 'will be able to → can', "fix": 'can'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bwill\s+not\b""", re.IGNORECASE),
     "msg": 'will not → does not', "fix": 'does not'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bcould\b\s""", re.IGNORECASE),
     "msg": 'could → can', "fix": 'can '},
    {"type": 'replace',
     "pattern": re.compile(r"""\b(?:may|might)\s+be\b""", re.IGNORECASE),
     "msg": 'may/might be → is', "fix": 'is'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bright\b(?!\s*(?:click|arrow|side|panel|column|margin|hand))""", re.IGNORECASE),
     "msg": 'right → correct', "fix": 'correct'},
    {"type": 'replace',
     "pattern": re.compile(r"""\bwrong\b""", re.IGNORECASE),
     "msg": 'wrong → incorrect', "fix": 'incorrect'},
    {"type": 'replace',
     "pattern": re.compile(r"""\band/or\b""", re.IGNORECASE),
     "msg": 'and/or → and', "fix": 'and'},
    {"type": 'replace',
     "pattern": re.compile(r"""\s*[\u2013\u2014]\s*"""),
     "msg": 'em/en dash → comma', "fix": ', '},
    {"type": 'replace',
     "pattern": re.compile(r"""[ \t]{2,}"""),
     "msg": 'double space → single space', "fix": ' '},
    {"type": 'replace',
     "pattern": re.compile(r"""\s+([,.!?:;])"""),
     "msg": 'space before punctuation removed', "fix": '$1'},
]


# =============================================================================
# SENTENCE-LEVEL CHECKS
# =============================================================================


def check_sentence_level(text):
    """
    Check for sentence-level violations:
    - Sentences exceeding 25 words
    - Numbers at the start of a sentence
    Returns list of violation dicts.
    """
    out = []
    sent_pat = re.compile(r"[^.!?\n]+[.!?]")
    for m in sent_pat.finditer(text):
        words = [w for w in m.group().strip().split() if w]
        if len(words) > 25:
            out.append({
                "start": m.start(), "end": m.end(),
                "ruleId": "sentence_length", "cat": "Grammar",
                "msg": f"Sentence is {len(words)} words (maximum: 25). Split into shorter sentences.",
                "matchText": m.group()[:60] + "\u2026",
                "color": "ca-structure"
            })

    num_start = re.compile(r"(?:^|[.!?]\s{1,4})(\d+)\s", re.MULTILINE)
    for m in num_start.finditer(text):
        idx = text.index(m.group(1), m.start())
        out.append({
            "start": idx, "end": idx + len(m.group(1)),
            "ruleId": "number_sentence_start", "cat": "Numbers",
            "msg": "Spell out numbers at the start of a sentence.",
            "matchText": m.group(1), "color": "ca-warn"
        })

    return out


def check_sentence_length(text):
    """
    Check for sentences exceeding 25 words in rewritten output.
    Returns list of warning dicts with original sentence and note.
    """
    violations = []
    rx = re.compile(r"[^.!?\n]+[.!?]")
    for m in rx.finditer(text):
        words = [w for w in m.group().strip().split() if w]
        if len(words) > 25:
            violations.append({
                "original": m.group().strip(),
                "note": f"Sentence has {len(words)} words. Split into \u226425 words."
            })
    return violations
